#!/usr/bin/env bash
# moveToZip.sh v0.2
# By: Stephan Sokolow (deitarion/SSokolow)
# $Revision$

source unball --source # Why keep two copies of the abspath() function?

function show_version() {
    echo "moveToZip v0.2"
    exit 0
}

function show_help() {
    echo "Usage: $0 directory ..."
    echo "Safely move one or more directories into ZIP archives with the same parent directory."
    exit 0
}

# Check whether we should display help
([ "$1" = '-h' ] || [ "$1" = '-?' ] || [ "$1" = '--help' ] || [ "$#" = 0 ]) && show_help
([ "$1" = '-v' ] || [ "$1" = "--version" ]) && show_version

for FILE in "$@"; do
	srcdir=`realpath "${FILE%/}"`
	pushd "${srcdir%/*}" > /dev/null
	zip -rTm "${srcdir##*/}".zip "${srcdir##*/}"
	popd > /dev/null
done
